src/Pozzani.Tickets/Models/Ticket.cs
using Pozzani.Tickets.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pozzani.Tickets.Models
{
    public class Ticket
    {
        /// <summary>
        /// Account Statuses
        /// </summary>
        public enum StatusItems
        {
            New,
            UnAssigned,
            Assigned,
            Paused,
            Awaiting_Feedback,
            Completed,
            Deleted
        }

        public enum PriorityItems
        {
            Low,
            Medium,
            High,
            Urgent,
            Critical
        }

        /// <summary>
        /// Unique Id for ticket
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Ticket description
        /// </summary>
        [Required]
        [AllowHtml]
        public string Description { get; set; }

        /// <summary>
        /// Displays a shorter version of the description limited to 253 chars
        /// </summary>
        public string ShortDescription
        {
            get
            {
                if (Description.Length > 250)
                {
                    return Description.Substring(0, 250) + "...";
                }

                return Description;
            }
        }

        /// <summary>
        /// Time stamp for when ticket was created
        /// </summary>
        [Display(Name = "Date Submitted")]
        public DateTime DateSubmitted { get; set; }

        /// <summary>
        /// Time stamp for when ticket was last updated
        /// </summary>
        [Display(Name = "Last Updated")]
        public DateTime DateLastUpdated { get; set; }

        /// <summary>
        /// Time stamp for when ticket was completed
        /// </summary>
        [Display(Name = "Date Completed")]
        public DateTime? DateCompleted { get; set; }

        /// <summary>
        /// User that the ticket is assigned to
        /// </summary>
        [ForeignKey("AssignedTo")]
        [CascadeDelete]
        [Display(Name = "Assigned To")]
        public int? AssignedToId { get; set; }

        /// <summary>
        /// User that submitted the original ticket
        /// </summary>
        [ForeignKey("SubmittedBy")]
        [CascadeDelete]
        [Display(Name = "Submitted By")]
        public int SubmittedById { get; set; }

        /// <summary>
        /// Ticket type Id
        /// </summary>
        [ForeignKey("TicketType")]
        [Display(Name = "Ticket Type")]
        public int TicketTypeId { get; set; }

        /// <summary>
        /// Current Status of Ticket
        /// </summary>
        public StatusItems Status { get; set; }

        public PriorityItems Priority { get; set; }

        /// <summary>
        /// This is for the ordering of jobs 1 being the 1st ticket to action
        /// </summary>
        [Display(Name = "Priority Level")]
        public int PriorityLevel { get; set; }

        /// <summary>
        /// Link to User class for assigned users
        /// </summary>
        public virtual User AssignedTo { get; set; }

        /// <summary>
        /// Link to User class for submitted users
        /// </summary>
        public virtual User SubmittedBy { get; set; }

        /// <summary>
        /// Link to TicketType class for ticket types
        /// </summary>
        public virtual TicketType TicketType { get; set; }

        /// <summary>
        /// Complete list of notes for this ticket
        /// </summary>
        public virtual List<Note> Notes { get; set; }
    }
}

src/Pozzani.Tickets/Models/TicketType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pozzani.Tickets.Models
{
    public class TicketType
    {
        /// <summary>
        /// Ticket Type Id
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Name of ticket type
        /// </summary>
        public string Name { get; set; }
    }
}

src/Pozzani.Tickets/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pozzani.Tickets.Data;
using Pozzani.Tickets.Models;
using System.Text.RegularExpressions;

namespace Pozzani.Tickets.Controllers
{
    public class TicketsController : Controller
    {
        private Context db = new Context();
        private AuthRepository _authRepository = null;
        private User.AccessLevelList[] _accessList = null;
        private NoteRepository noteRepository = null;
        private TicketsRepository ticketsRepository = null;
        private GoogleRepository googleRepository = null;

        public TicketsController()
        {
            _authRepository = new AuthRepository();
            noteRepository = new NoteRepository();

            _accessList = new[] {
                Models.User.AccessLevelList.IT,
                Models.User.AccessLevelList.Super,
                Models.User.AccessLevelList.Office
            };

            ViewBag.AccessList = _accessList;
        }

        // GET: Tickets
        [RedirectActionAttribute]
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: Tickets/Details/5
        [RedirectActionAttribute]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);

            // Update ticket status
            ticketsRepository = new TicketsRepository();
            ticketsRepository.UpdateStatusIfNew(ticket.Id);

            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        [RedirectActionAttribute]
        public ActionResult Create()
        {
            UserRepository userRepository = new UserRepository();
            
            ViewBag.AssignedToId = new SelectList(userRepository.GetITUsers(), "Id", "Name");
            ViewBag.SubmittedById = new SelectList(userRepository.GetAllUsers(), "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
            ViewBag.Priority = new SelectList(Enum.GetValues(typeof(Ticket.PriorityItems)));

            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RedirectActionAttribute]
        public ActionResult Create(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.DateSubmitted = DateTime.Now;
                ticket.DateLastUpdated = DateTime.Now;
                ticket.Status = Ticket.StatusItems.New;

                // Remove scripts from html string
                Regex rRemScript = new Regex(@"<script[^>]*>[\s\S]*?</script>");
                ticket.Description = rRemScript.Replace(ticket.Description, "");

                db.Tickets.Add(ticket);
                db.SaveChanges();

                // Append to Sheet
                //googleRepository = new GoogleRepository();
                //googleRepository.AddNewRow(ticket);
                
                return RedirectToAction("Index");
            }

            ViewBag.AssignedToId = new SelectList(db.Users, "Id", "Name", ticket.AssignedToId);
            ViewBag.SubmittedById = new SelectList(db.Users, "Id", "Name", ticket.SubmittedById);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            ViewBag.Priority = new SelectList(Enum.GetValues(typeof(Ticket.PriorityItems)));

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        [RedirectActionAttribute]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            UserRepository userRepository = new UserRepository();

            ViewBag.AssignedToId = new SelectList(userRepository.GetITUsers(), "Id", "Name", ticket.AssignedToId);
            ViewBag.SubmittedById = new SelectList(userRepository.GetAllUsers(), "Id", "Name", ticket.SubmittedById);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            ViewBag.Priority = new SelectList(Enum.GetValues(typeof(Ticket.PriorityItems)), ticket.Priority);

            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RedirectActionAttribute]
        public ActionResult Edit(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                // Remove scripts from html string
                Regex rRemScript = new Regex(@"<script[^>]*>[\s\S]*?</script>");
                ticket.Description = rRemScript.Replace(ticket.Description, "");

                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();

                // Update Sheets
                //googleRepository = new GoogleRepository();
                //googleRepository.UpdateRow(ticket);

                return RedirectToAction("Index");
            }
            ViewBag.AssignedToId = new SelectList(db.Users, "Id", "Name", ticket.AssignedToId);
            ViewBag.SubmittedById = new SelectList(db.Users, "Id", "Name", ticket.SubmittedById);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
            ViewBag.Priority = new SelectList(Enum.GetValues(typeof(Ticket.PriorityItems)), ticket.Priority);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        [RedirectActionAttribute]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            ticket.Status = Ticket.StatusItems.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RedirectActionAttribute]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AssignToMe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Where(x => x.Id == id).SingleOrDefault();
            ticket.AssignedToId = AuthRepository.GetUser().Id;
            ticket.Status = Ticket.StatusItems.Assigned;
            db.SaveChanges();

            if (ticket == null)
            {
                return HttpNotFound();
            }

            // Add a note to the Ticket to say it's been assigned to
            noteRepository.AddAssignedNote(ticket.Id, AuthRepository.GetUser());

            TempData["success"] = "This ticket is now assigned to you.";
            return View("Details", ticket);
        }

        public ActionResult Complete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Where(x => x.Id == id).SingleOrDefault();
            ticket.Status = Ticket.StatusItems.Completed;
            db.SaveChanges();

            if (ticket == null)
            {
                return HttpNotFound();
            }

            // Add a note to the Ticket to say it's been assigned to
            noteRepository.CompletedNote(ticket.Id, AuthRepository.GetUser());

            TempData["success"] = "This ticket is now completed.";
            return View("Details", ticket);
        }
    }
}

src/Pozzani.Tickets/Views/Tickets/Create.cshtml
@model Pozzani.Tickets.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 5, 100, new { @class = "form-control", id = "summernote" } )
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedToId, "Assigned To", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AssignedToId", null, " - ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssignedToId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmittedById, "Submitted By", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubmittedById", null, " - ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubmittedById, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketTypeId, "Ticket Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, "Priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Priority", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Pozzani.Tickets/Views/Tickets/Delete.cshtml
@model Pozzani.Tickets.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssignedTo.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedTo.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmittedBy.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmittedBy.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicketType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSubmitted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateLastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateLastUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/Pozzani.Tickets/Views/Tickets/Details.cshtml
@model Pozzani.Tickets.Models.Ticket
@using Pozzani.Tickets.Models
@using Pozzani.Tickets.Data

@{
    ViewBag.Title = "Ticket Details";
    var assignedTo = (Model.AssignedTo == null ? "Nobody" : Model.AssignedTo.Name);
    UserRepository userRepository = new UserRepository();
    Note note = new Note();
    List<Note> notes = Model.Notes;
    notes.Reverse();

}

<div class="row">

    <div class="alert alert-danger text-center col-xs-12"><strong>@Html.DisplayNameFor(model => model.Priority) - @Html.DisplayFor(model => model.Priority)</strong></div>

    <div class="col-md-6">

        <div class="well">
            <h4><strong>Ticket ID #@Html.DisplayFor(model => model.Id)</strong></h4>
            <h4>@Html.Raw(Model.Description)</h4>
        </div>

        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered table-striped table-responsive">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.SubmittedById)</th>
                        <td>@Html.DisplayFor(model => model.SubmittedBy.Name)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.AssignedToId)</th>
                        <td>@assignedTo</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.TicketTypeId)</th>
                        <td>@Html.DisplayFor(model => model.TicketType.Name)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.PriorityLevel)</th>
                        <td>@Html.DisplayFor(model => model.PriorityLevel)</td>
                    </tr>
               </table>
                @if (AuthRepository.GetUser().Id == Model.AssignedToId)
                {
                    @Html.ActionLink("Assign to me", "AssignToMe", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-success btn-sm", disabled = "disabled" })
                }
                else
                {
                    @Html.ActionLink("Assign to me", "AssignToMe", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-success btn-sm" })
                }

                @Html.ActionLink("Edit", "Edit", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
                @Html.ActionLink("Delete", "Delete", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-danger btn-sm" })
                @if (Model.Status == Ticket.StatusItems.Completed)
                {
                    @Html.ActionLink("Complete", "Complete", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-info btn-sm", disabled = "disabled" })
                }
                else
                {
                    @Html.ActionLink("Complete", "Complete", "Tickets", new { Id = Model.Id }, new { @class = "btn btn-info btn-sm" })
                }
                
            </div>

            <div class="col-md-6">
                <table class="table table-bordered table-responsive table-striped">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.DateSubmitted)</th>
                        <td>@Html.DisplayFor(model => model.DateSubmitted)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.DateLastUpdated)</th>
                        <td>@Html.DisplayFor(model => model.DateLastUpdated)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.DateCompleted)</th>
                        <td>@Html.DisplayFor(model => model.DateCompleted)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Status)</th>
                        <td>@Html.DisplayFor(model => model.Status)</td>
                    </tr>
                </table>
            </div>
        </div>

        @Html.Partial("~/Views/Notes/Create.cshtml",new Note(), new ViewDataDictionary { { "ticketId", Model.Id } })    

    </div>

    <div class="col-md-6">
    @foreach(var item in notes)
        {
            <div class="alert @(item.SubmittedByID == Model.SubmittedBy.Id ? "alert-info" : "alert-warning")">
                <div class="row">
                    <div class="col-xs-12">
                        @Html.Raw(item.Description)
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-xs-12">
                        <div class="label label-primary pull-right">@item.DateSubmitted</div>
                        <div class="label label-success">@userRepository.GetUserById(item.SubmittedByID).Name</div>
                        <div class="label label-default">Time: @item.Minutes</div>
                    </div>
                </div>
            </div>
        }
    </div>

</div>
<hr />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Pozzani.Tickets/Views/Tickets/Edit.cshtml
@model Pozzani.Tickets.Models.Ticket

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 5, 100, new { @class = "form-control", id = "summernote" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedToId, "Assigned To", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AssignedToId", null, " - ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssignedToId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmittedById, "Submitted By", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubmittedById", null, " - ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubmittedById, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketTypeId, "Ticket Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, "Priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Priority", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Pozzani.Tickets/Views/Tickets/Index.cshtml
@model IEnumerable<Pozzani.Tickets.Models.Ticket>

@{
    ViewBag.Title = "Tickets";
}

@Html.ActionLink("Add Ticket", "Create", "Tickets", new { @class = "pull-right btn btn-primary" })
<h2>@ViewBag.Title</h2>

@ViewBag.ErrorMessage

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AssignedToId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubmittedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateLastUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedTo.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubmittedBy.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TicketType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateSubmitted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateLastUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCompleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>