src/Pozzani.Tickets/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pozzani.Tickets.Models
{
    public class Note
    {
        /// <summary>
        /// Unique Identifier
        /// </summary>
        [Key]
        public Int32 ID { get; set; }

        /// <summary>
        /// Note text
        /// </summary>
        [Required]
        [AllowHtml]
        public String Description { get; set; }

        /// <summary>
        /// Time taken
        /// </summary>
        public Int32 Minutes { get; set; }

        /// <summary>
        /// Date / Time Stramp for note
        /// </summary>
        public DateTime DateSubmitted { get; set; }

        /// <summary>
        /// User that entered note
        /// </summary>
        [ForeignKey("User")]
        public Int32 SubmittedByID { get; set; }
        public virtual User User { get; set; }

        /// <summary>
        /// Ticket that note is referring to
        /// </summary>
        [ForeignKey("Ticket")]
        public Int32 TicketID { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}

src/Pozzani.Tickets/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pozzani.Tickets.Data;
using Pozzani.Tickets.Models;
using System.Text.RegularExpressions;

namespace Pozzani.Tickets.Controllers
{
    public class NotesController : Controller
    {
        private Context db = new Context();
        private AuthRepository _authRepository = null;
        private User.AccessLevelList[] _accessList = null;

        public NotesController()
        {
            _authRepository = new AuthRepository();

            _accessList = new[] {
                Models.User.AccessLevelList.IT,
                Models.User.AccessLevelList.Super
            };

            ViewBag.AccessList = _accessList;
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            ViewBag.TicketID = new SelectList(db.Tickets, "Id", "Description");
            ViewBag.SubmittedByID = new SelectList(db.Users, "Id", "Username");
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                note.DateSubmitted = DateTime.Now;
                note.SubmittedByID = AuthRepository.GetUser().Id;

                // Remove scripts from html string
                Regex rRemScript = new Regex(@"<script[^>]*>[\s\S]*?</script>");
                note.Description = rRemScript.Replace(note.Description, "");

                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { Id = note.TicketID });
            }

            TempData["error"] = "Please enter a note before clicking the button!";
            return RedirectToAction("Details", "Tickets", new { Id = note.TicketID });
        }

       // GET: Notes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Pozzani.Tickets/Views/Notes/Create.cshtml
@model Pozzani.Tickets.Models.Note

@using (Html.BeginForm("Create","Notes")) 
{
    @Html.AntiForgeryToken()
    
        <h4>Add Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-labe" })
            @Html.TextAreaFor(model => model.Description, 5, 10, new { @class = "form-control", id = "summernote" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Minutes, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Minutes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Minutes, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="pull-right">
                <input type="submit" value="Add Note" class="btn btn-primary" />
                @Html.Hidden("TicketId",ViewData["ticketId"])
            </div>
        </div>
}